dct = {
    'UZ': {
        "📚Kurslar": "📚Kurslar",
        "👨‍💻O'qituvchilar": "👨‍💻O'qituvchilar",
        "📍Manzilimiz": "📍Manzilimiz",
        "ℹ️Biz haqimizda": "ℹ️Biz haqimizda",
        "📱Biz bilan bog'lanish": "📱Biz bilan bog'lanish",
        "Menyu elementlaridan birini tanlang": "Menyu elementlaridan birini tanlang",
        "🎛Asosiy Menyu": "🎛Asosiy Menyu",
        "Darsni tanlang": "Darsni tanlang",
        "⬅️Orqaga": "⬅️Orqaga",
        "⚙️Tilni o'zgartirish": "⚙️Tilni o'zgartirish",
        "Qaysi o`qituvchi haqida ma`lumot olmoqchisiz?": "Qaysi o`qituvchi haqida ma`lumot olmoqchisiz?",
        "Iltimos ro`yhatdaki o`qituvchilardan birini tanlang": "Iltimos ro`yhatdaki o`qituvchilardan birini tanlang",
        "Manzil: Urganch shahri, Yoshlik ko'chasi 26-uy\nMo'ljal:Urganch temir yo'l vokzali": "Manzil: Urganch shahri, Yoshlik ko'chasi 26-uy\nMo'ljal:Urganch temir yo'l vokzali",
        "Arizangiz uchun rahmat, menedjerlarimiz siz bilan tez orada bog`lanishadi.": "Arizangiz uchun rahmat, menedjerlarimiz siz bilan tez orada bog`lanishadi.",
        "Sizning so`rovingiz ko`rib chiqilmoqda, iltimos menedjerlar qo`ng`iroqini kuting": "Sizning so`rovingiz ko`rib chiqilmoqda, iltimos menedjerlar qo`ng`iroqini kuting",
        "📱Telefon raqamimni yuborish": "📱Telefon raqamimni yuborish",
        "Siz bilan bog`lanish uchun telefon raqamingizni yuboring": "Siz bilan bog`lanish uchun telefon raqamingizni yuboring",
        "Uzingni kontaktingizni yuboring!!": "Uzingni kontaktingizni yuboring!!",
        "Toliq ism familiyangizni kiriting": "Toliq ism familiyangizni kiriting",
        "Iltimos Ism Familiyangizni Tog`ri kiriting!!!": "Iltimos Ism Familiyangizni Tog`ri kiriting!!!",
        "🇺🇿Iltimos tilni tanlang": "🇺🇿Iltimos tilni tanlang",
        "Qaysi kursga a'zo bo'lmoqchisiz?": "Qaysi kursga a'zo bo'lmoqchisiz?",
        "✉ Yangilik yaratish": "✉ Yangilik yaratish",
        "Bekor qilindi❌": "Bekor qilindi❌",
        "Bekor qilish❌": "Bekor qilish❌",
        "Yuborish✅": "Yuborish✅",
        "Yangiliklar muvaffaqiyatli qo'shildi✅": "Yangiliklar muvaffaqiyatli qo'shildi✅",
        "Yaxshi! Yangiliklar faqat matndan iborat bo'lishi kerak\nMenga sms yozing va men barcha foydalanuvchilarga yangiliklar to'g'risida xabar beraman": "Yaxshi! Yangiliklar faqat matndan iborat bo'lishi kerak\nMenga sms yozing va men barcha foydalanuvchilarga yangiliklar to'g'risida xabar beraman",
    },
    'RU': {
        "📚Kurslar": "📚Курсы",
        "👨‍💻O'qituvchilar": "👨‍💻Учителя",
        "📍Manzilimiz": "📍Наш адресс",
        "ℹ️Biz haqimizda": "ℹО нас",
        "📱Biz bilan bog'lanish": "📱Связаться с нами",
        "Menyu elementlaridan birini tanlang": "Пожалуйста, выберите один из пунктов меню",
        "🎛Asosiy Menyu": "🎛Главное меню",
        "Darsni tanlang": "Выберите урок",
        "⬅️Orqaga": "⬅️Назад",
        "⚙️Tilni o'zgartirish": "⚙️Изменить язык",
        "Qaysi o`qituvchi haqida ma`lumot olmoqchisiz?": "Про какого учителя вы хотите получить информацию?",
        "Iltimos ro`yhatdaki o`qituvchilardan birini tanlang": "Пожалуйста, выберите учителя из списка",
        "Manzil: Urganch shahri, Yoshlik ko'chasi 26-uy\nMo'ljal:Urganch temir yo'l vokzali": "Адрес: город Ургенч, улица Ёшлика 26\nНаправление: Железно дорожный вокзал Ургенч",
        "Arizangiz uchun rahmat, menedjerlarimiz siz bilan tez orada bog`lanishadi.": "Спасибо за заявку, наши менеджеры свяжутся с вами в ближайшее время.",
        "Sizning so`rovingiz ko`rib chiqilmoqda, iltimos menedjerlar qo`ng`iroqini kuting": "Ваш запрос обрабатывается, ждите звонка от менеджеров",
        "📱Telefon raqamimni yuborish": "📱Отправить номер телефона",
        "Siz bilan bog`lanish uchun telefon raqamingizni yuboring": "Отправьте свой номер телефона, чтобы с вами связаться",
        "Uzingni kontaktingizni yuboring!!": "Пожалуйста, пришлите свой номер телефона",
        "Toliq ism familiyangizni kiriting": "Пожалуйста введите свое полное имя",
        "Iltimos Ism Familiyangizni Tog`ri kiriting!!!": "Пожалуйста, введите ваше полное имя правильно",
        "🇺🇿Iltimos tilni tanlang": "🇷🇺Пожалуйста выберите язык интерфейся бота",
        "Qaysi kursga a'zo bo'lmoqchisiz?": "Какой курс вы хотите выбрать?",
        "✉ Yangilik yaratish": "✉ Добавить новость",
        "Bekor qilindi❌": "Отменён❌",
        "Bekor qilish❌": "Отменить❌",
        "Yuborish✅": "Отправить✅",
        "Yangiliklar muvaffaqiyatli qo'shildi✅": "Новость успешно добавлен✅",
        "Yaxshi! Yangiliklar faqat matndan iborat bo'lishi kerak\nMenga sms yozing va men barcha foydalanuvchilarga yangiliklar to'g'risida xabar beraman": "Отлично! Новость должен состоять только из текста\nНапишите мне текстое сообщение и я сообщу всем пользователям о новосте",
    },
    'EN': {
        "📚Kurslar": "📚Courses",
        "👨‍💻O'qituvchilar": "👨‍💻Mentors",
        "📍Manzilimiz": "📍Address",
        "ℹ️Biz haqimizda": "ℹ️About Us",
        "📱Biz bilan bog'lanish": "📱Contact Us",
        "Menyu elementlaridan birini tanlang": "Please select one of the menu items",
        "🎛Asosiy Menyu": "🎛Main Menu",
        "Darsni tanlang": "Select the Lesson",
        "⬅️Orqaga": "⬅️Back",
        "⚙️Tilni o'zgartirish": "⚙️Change the language",
        "Qaysi o`qituvchi haqida ma`lumot olmoqchisiz?": "Which Mentor do you want to know?",
        "Iltimos ro`yhatdaki o`qituvchilardan birini tanlang": "Please select the Mentor from the list",
        "Manzil: Urganch shahri, Yoshlik ko'chasi 26-uy\nMo'ljal:Urganch temir yo'l vokzali": "Address: Urgench city, Yoshlik street 26\nDestination: Urgench railway station",
        "Arizangiz uchun rahmat, menedjerlarimiz siz bilan tez orada bog`lanishadi.": "Thank you for your application, our managers will contact you soon.",
        "Sizning so`rovingiz ko`rib chiqilmoqda, iltimos menedjerlar qo`ng`iroqini kuting": "Your request is being processed, please wait for a call from the managers",
        "📱Telefon raqamimni yuborish": "📱Send your the phone number",
        "Siz bilan bog`lanish uchun telefon raqamingizni yuboring": "Send your phone number to contact you",
        "Uzingni kontaktingizni yuboring!!": "Please send your phone number",
        "Toliq ism familiyangizni kiriting": "Please enter your full name",
        "Iltimos Ism Familiyangizni Tog`ri kiriting!!!": "Please enter your full name correctly",
        "🇺🇿Iltimos tilni tanlang": "🇬🇧Please select a language",
        "Qaysi kursga a'zo bo'lmoqchisiz?": "Which course do you want to take?",
        "✉ Yangilik yaratish": "✉ Add News",
        "Bekor qilindi❌": "Canceled❌",
        "Bekor qilish❌": "Cancel❌",
        "Yuborish✅": "Send✅",
        "Yangiliklar muvaffaqiyatli qo'shildi✅": "News successfully added✅",
        "Yaxshi! Yangiliklar faqat matndan iborat bo'lishi kerak\nMenga sms yozing va men barcha foydalanuvchilarga yangiliklar to'g'risida xabar beraman": "Fine! The news should consist only of text\nWrite me a text message and I will inform all users about the news",
    }
}